export const DEFAULT_BORDER_RADIUS = 3
export const DEFAULT_BUTTON_PADDING_Y = 5
export const DEFAULT_BUTTON_PADDING_X = 15

export const SPACING_SMALL = 5
export const SPACING_REGULAR = 10
export const SPACING_MID = 15
export const SPACING_BIG = 25

export const APP_HEADER_HEIGHT = 65

export const CONTAINER_PADDING = APP_HEADER_HEIGHT + 20

export const TIME_ENTRY_SECTION_HEIGHT = 100
export const ENTRY_DESCRIPTION_FIELD_WIDTH = 350
export const ENTRY_DESCRIPTION_FIELD_HEIGHT = 100

export const LABEL_WRAPPER_WIDTH = 500
export const LABEL_PADDING = SPACING_REGULAR
export const LABEL_HEIGHT = 30
export const LABEL_MARGIN = SPACING_MID
export const LABEL_WIDTH = 100

export const TIME_FIELD_WIDTH = 90
export const TIME_FIELD_MARGIN = 7

export const ENTRY_LIST_MARGIN_TOP = 50
export const ENTRY_LIST_PADDING_TOP = SPACING_MID
export const ENTRY_LIST_ITEM_PADDING = SPACING_REGULAR
export const ENTRY_LIST_ITEM_MARGIN = SPACING_MID

export const FOOTER_PADDING = SPACING_MID
export const FOOTER_HEIGHT = 50

export const Z_INDEX_MIN = 0
export const Z_INDEX_REGULAR = 100
export const Z_INDEX_MID = 200
